### ISSUE TITLE
AttributeError: 'exceptions.KeyError' object has no attribute 'msg'

### ISSUE THREAD

**Issue by b97pla** [NationalGenomicsInfrastructure/ngi_pipeline#294]
Traceback (most recent call last):
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/mock.py", line 1201, in patched
        return func(*args, **keywargs)
      File "/home/travis/build/SciLifeLab/taca-ngi-pipeline/tests/test_deliver.py", line 97, in test_fetch_sample_db_entry
        self.deliverer.sample_entry(),
      File "build/bdist.linux-x86_64/egg/ngi_pipeline/utils/classes.py", line 48, in __call__
        return_val = self.func(*args)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/taca_ngi_pipeline-0.1.1-py2.7.egg/taca_ngi_pipeline/deliver/deliver.py", line 95, in sample_entry
        self.dbcon().sample_get,self.projectid,self.sampleid)
      File "build/bdist.linux-x86_64/egg/ngi_pipeline/utils/classes.py", line 48, in __call__
        return_val = self.func(*args)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/taca_ngi_pipeline-0.1.1-py2.7.egg/taca_ngi_pipeline/deliver/deliver.py", line 65, in dbcon
        return db.CharonSession()
      File "build/bdist.linux-x86_64/egg/ngi_pipeline/database/classes.py", line 19, in __call__
        cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
      File "build/bdist.linux-x86_64/egg/ngi_pipeline/database/classes.py", line 41, in __init__
        raise ValueError('Unable to load needed Charon variable: {}'.format(e.msg))
    AttributeError: 'exceptions.KeyError' object has no attribute 'msg'

**Comment by mariogiov** [comment]
Son of a beesting

**Comment by mariogiov** [comment]
I fix

**Comment by mariogiov** [comment]
Although it does still get the point across
